my_project:
  outputs:
    dev:
      dbname: your_postgres_db_name
      host: docker_container_name_for_postgres
      pass: your_db_password
      port: 5432
      schema: dev
      threads: 4
      type: postgres
      user: your_db_user
  target: dev
