my_project:
  outputs:
    dev:
      dbname: weather_api
      host: postgres_container
      pass: db_password
      port: 5432
      schema: dev
      threads: 4
      type: postgres
      user: db_user
  target: dev
